import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link";

const scipio = localFont({
  src: "./fonts/Scipio-Regular-Exfontbff2.otf",
  variable: "--font-scipio",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${scipio.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background">
        <header className="flex justify-between items-center bg-container p-8 shadow-2xl">
          <h1 className="text-xl md:text-4xl text-white font-scipio">
            RevoShop
          </h1>

          <nav className="">
            <ul className="flex justify-between items-center gap-8 text-white">
              <li className="cursor-pointer font-scipio bg-background text-xs md:text-sm py-1 px-4 rounded-2xl">
                <Link href="/login">Masuk</Link>
              </li>
              <li className="cursor-pointer font-scipio text-xs md:text-sm text-background bg-white px-4 py-1 rounded-2xl">
                <Link href="/register">Daftar</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>






      </body>
    </html>
  );
}
