import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Link from "next/link";
import { FaGithub, FaWhatsapp, FaInstagram } from "react-icons/fa"

const scipio = localFont({
  src: "./fonts/Scipio-Regular-Exfontbff2.otf",
  variable: "--font-scipio",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${scipio.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background">
        <header className="flex justify-between items-center bg-container p-8 shadow-2xl">
          <h1 className="text-xl md:text-4xl text-white font-scipio">
            RevoShop
          </h1>

          <nav className="">
            <ul className="flex justify-between items-center gap-8 text-white">
              <li className="cursor-pointer font-scipio bg-background text-xs md:text-sm py-1 px-4 rounded-2xl">
                <Link href="/login">Masuk</Link>
              </li>
              <li className="cursor-pointer font-scipio text-xs md:text-sm text-background bg-white px-4 py-1 rounded-2xl">
                <Link href="/register">Daftar</Link>
              </li>
            </ul>
          </nav>
        </header>

        <main>{children}</main>


        
        <footer className="bg-container">

            <div className="flex justify-between px-8 py-4">
                  <h2 className="font-scipio text-white text-3xl">RevoShop</h2>

                  <ul className="flex justify-center items-center gap-4">
                     <a href="">
                        <FaGithub className="w-8 h-8 active:scale-95 transition transform hover:-y-translate-1 text-teks hover:text-black"/>
                     </a> 
                     <a href="">
                        <FaWhatsapp className="w-8 h-8 active:scale-95 transition transform hover:-y-translate-1 text-teks hover:text-black"/>
                      </a>
                      <a href="">
                        <FaInstagram className="w-8 h-8 active:scale-95 transition transform hover:-y-translate-1 text-teks hover:text-black"/>
                      </a>
                  </ul>
            </div>

             <hr className="text-white"/>

             <p className="text-xs md:text-sm text-center my-2 text-teks">© 2025 RevoShop. All rights reserved.</p>

        </footer>


      </body>
    </html>
  );
}
